language: python

python:
- "pypy"
- "pypy3"
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- 3.5

sudo: false

install:
  # Coveralls 4.0 doesn't support Python 3.2
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
  - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi
  - npm install

script:
# Test Python:
- coverage run --include=lib/* -m nose --verbose
# Test Javascript:
- grunt
# Test Ruby:
- rake test

after_success:
- coverage report
- pip install coveralls
- coveralls

after_script:
- coverage report
- pip install pep8 pyflakes
- pep8 --statistics --count lib/*.py test/*.py
- pyflakes lib/*.py test/*.py | tee >(wc -l)
